name:Quick Link Check
on:
  workflow_dispatch:
jobs:
  link-check:
    runs-on:ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@v1.9.1
        with:
          fail: false
          args: >
            --no-progress
            --verbose
            "./**/*.md"
